### PR TITLE
Add some cool badges. Code Climate

### PR DESCRIPTION
**Pull request by sauloperez**
I opened a Code Climate account and added its badge

### CODE REVIEW

**Comment by andresgutgon** [comment]
:+1:

**Comment by enricostano** [comment]
> You're trying to set up a service hook for a repository that lives in the Open Source section of your Dashboard. Unfortunately we don't yet support service hooks for these repositories.

:sob: :sob: :sob:

**Comment by sauloperez** [comment]
Was that answer related to the coverage badge @enricostano ? I can remove it and merge this, so we move forward.

**Comment by andresgutgon** [comment]
Dale!

**Pull request merged**
