### PR TITLE
Hitting alfa stage

### PR DESCRIPTION
**Pull request by enricostano**
Yes, you got it: http://alfa.katuma.org is **ONLINE**

Now we'll deploy directly to this our first stage **ALFA** :tada: 

Enjoy! :smiley:

### CODE REVIEW

**Comment by naoisegolden** [comment]
:clap: :clap: :clap: :clap: :clap: :clap:

**Comment by enricostano** [comment]
Yeah the stack is pretty dense in the front-end, but it seems that there is no sane/lightweight way to get a maintainable UI nowadays. :trollface:

**Comment by sauloperez** [comment]
I honestly thought it was a joke... So happy to work on the backend xD

**Comment by enricostano** [comment]
@sauloperez :joy:

**Comment by andresgutgon** [comment]
Real women/men do frontend :trollface:

**Comment by sauloperez** [comment]
And that's no one solves the problems and every single day there's a new lib/approach :trollface:

**Pull request merged**
