### PR TITLE
Strategies for configuring actionmailer

### PR DESCRIPTION
**Pull request by rewritten**
This is what I had in mind to make configuration more generic. Not really for merge, just for opinions.

### CODE REVIEW

**Comment by rewritten** [comment]
cc: @enricostano

**Comment by rewritten** [comment]
I haven't tried to run it... :sweat:

**Comment by enricostano** [comment]
@rewritten many thanks for the contribution! :muscle: 

Would be nice to place those strategies in some common place to use/enable them in other environments like `staging` (still not present), etc. and to to avoid putting too much stuff in `config/environments/production.rb`.

But yes I like the idea :smiley:

**Comment by enricostano** [comment]
BTW, it's possible that for the beta we'll only adopt the second strategy, the one with multiple ENV variables. We can surely use the different strategies right after beta stage.

**Comment by enricostano** [comment]
We merged https://github.com/coopdevs/katuma/pull/67 with a generic SMTP configuration delegated to specific environment variables. In the future, after **alfa** and **beta** I think that we should be able to talk again about this. Many thanks for your contribution!

Of course feel free to re-open it if you think it's still relevant! :smiley: :

**Comment by rewritten** [comment]
No prob, I think this "concept" anyway was too generic to be merged now. Cheers :)

**Pull request closed without merging**
